title: A Step Above Industrial Inc.
email: astepabove.ca@gmail.com
phone: "778-580-7996"

# Theme settings
theme_color: "#0a2540" # Deep Navy Blue
accent_color: "#20a4f3" # High-visibility Blue/Teal

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

permalink: pretty

collections:
  services:
    output: true
    sort_by: weight
    permalink: /services/:name/

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
